CREATE TABLE @schemaName.incidence_summary
(  
	ref_id int,
	source_name varchar(255),
	target_cohort_definition_id bigint,
	target_name varchar(255),
	tar_id bigint,
	tar_start_with varchar(10),
	tar_start_offset bigint,
	tar_end_with varchar(10),
	tar_end_offset bigint,
	subgroup_id bigint,
	subgroup_name varchar(255),
	outcome_id bigint,
	outcome_cohort_definition_id bigint,
	outcome_name varchar(255),
	clean_window bigint,
	age_id int,
	age_group_name varchar(255),
	gender_id int,
	gender_name varchar(255),
	start_year int,
	persons_at_risk_pe bigint,
	persons_at_risk bigint,
	person_days_pe bigint,
	person_days bigint,
	person_outcomes_pe bigint,
	person_outcomes bigint,
	outcomes_pe bigint,
	outcomes bigint,
	incidence_proportion_p100p float,
	incidence_rate_p100py float
 );